### ISSUE TITLE
cancel a particular local notification in android

### ISSUE THREAD

**Issue by devekoperiOS** [zo0r/react-native-push-notification#105]
Please let me know that how can I cancel a particular local notification in android?

**Comment by varungupta85** [comment]
+1

**Comment by npomfret** [comment]
This is implemented is master now, but not released yet.  Would you be able to help test it before we push the release?

**Comment by robinmitra** [comment]
I'd love to help since I need this too. How can I help with testing?

**Comment by npomfret** [comment]
Just try out the master branch.

**Comment by robinmitra** [comment]
Done. How do I test this particular feature? Is there any documentation for this?

**Comment by npomfret** [comment]
Check the readme

**Comment by jsdario** [comment]
I believed there was a merge about this, but cannot see issues close. Is this problem persisting?

**Comment by npomfret** [comment]
No, I understand its working.  We can close.
