### ISSUE TITLE
WAKE_LOCK Android permission is no longer necessary since GCM deprecation in favor of FCM

### ISSUE THREAD

**Issue by sunweiyang** [zo0r/react-native-push-notification#1494]
Google's official docs for migrating from GCM to FCM recommends to remove WAKE_LOCK permission:
https://developers.google.com/cloud-messaging/android/android-migrate-fcm

Since wake locks incur a significant penalty to battery life, can this library's documentation be updated to reflect this move to FCM?

**Comment by Dallas62** [comment]
Hi @sunweiyang 
Thanks for this, this will be updated 😉

**Comment by Dallas62** [comment]
Hi, the release `4.0.0` of the library should solve this issue, feel free to reopen if something is missing 😉

**Comment by yinka-optisoft** [comment]
It doesn't solve it. I'm presently using react-native-push-notification: "^6.0.0" and I do not get a push notification when the app is closed.

**Comment by Dallas62** [comment]
Hi,

You must create a channel, please read the readme for that.

Regards
