### ISSUE TITLE
Scheduling local push notifications without Firebase setup

### ISSUE THREAD

**Issue by DucAnhPhi** [zo0r/react-native-push-notification#1554]
Is it possible to schedule local push notifications without setting up Firebase integration?
I have changed the AndroidManifest.xml according to the README.

This is the error I get:
![grafik](https://user-images.githubusercontent.com/10599685/88297517-49331500-cd00-11ea-8c87-579bc03f1a16.png)

**Comment by Dallas62** [comment]
Hi @DucAnhPhi 
Yes, this is documented in the Usage part with `.configure` and `requestPermissions`.
There is also issues talking about it.
Regards,

**Comment by DucAnhPhi** [comment]
Thank you, it worked.

**Comment by tncbbthositg** [comment]
For folks who find this issue later, specifically the answer is this (in `.configure()`):

```
  /**
   * (optional) default: true
   * - Specified if permissions (ios) and token (android and ios) will requested or not,
   * - if not, you must call PushNotificationsHandler.requestPermissions() later
   * - if you are not using remote notification or do not have Firebase installed, use this:
   *     requestPermissions: Platform.OS === 'ios'
   */
  requestPermissions: true,
```

From this comment: https://github.com/zo0r/react-native-push-notification/issues/1763#issuecomment-735281950

**Comment by Balthazar33** [comment]
> For folks who find this issue later, specifically the answer is this (in `.configure()`):
> 
> ```
>   /**
>    * (optional) default: true
>    * - Specified if permissions (ios) and token (android and ios) will requested or not,
>    * - if not, you must call PushNotificationsHandler.requestPermissions() later
>    * - if you are not using remote notification or do not have Firebase installed, use this:
>    *     requestPermissions: Platform.OS === 'ios'
>    */
>   requestPermissions: true,
> ```
> 
> From this comment: [#1763 (comment)](https://github.com/zo0r/react-native-push-notification/issues/1763#issuecomment-735281950)

I've implemented this suggestion. Yet, I'm getting the following error.

`TypeError: (0, _NotificationService.default) is not a function. (In '(0, _NotificationService.default)()', '(0, _NotificationService.default)' is undefined)`

Any idea what might be causing this?

This is what my Notification config looks like:

```
import PushNotification from 'react-native-push-notification';
import {Platform} from 'react-native';
PushNotification.configure({
    onRegister: function (token) {
      console.log("TOKEN:", token);
    },
    onNotification: function (notification) {
      console.log("NOTIFICATION:", notification);
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
    onAction: function (notification) {
      console.log("ACTION:", notification.action);
      console.log("NOTIFICATION:", notification);
    },
    onRegistrationError: function(err) {
      console.error(err.message, err);
    },
    permissions: {
      alert: true,
      badge: true,
      sound: true,
    },
    popInitialNotification: true,
    requestPermissions: Platform.OS === 'ios',
  });

  PushNotification.createChannel(
    {
      channelId: "channel-id", // (required)
      channelName: "My channel", // (required)
      channelDescription: "A channel to categorise your notifications", // (optional) default: undefined.
      playSound: false, // (optional) default: true
      soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
      importance: 4, // (optional) default: 4. Int value of the Android notification importance
      vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
    },
    (created) => console.log(`createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
  );

 export const CallNotif = ()=>{
    PushNotification.popInitialNotification((notification) => {
        console.log('Initial Notification', notification);
      });
 };

```

**Comment by shrutiraoniit25** [comment]
make request permission : false,
and channel id: "channel_01"..I am attaching the screenshot it worked for me for local Notification

![Screenshot (26)](https://user-images.githubusercontent.com/42043257/121522315-9c927c80-ca12-11eb-9d63-91c9999c9247.png)
![Screenshot (27)](https://user-images.githubusercontent.com/42043257/121522320-9e5c4000-ca12-11eb-8b2d-b1e496988679.png)
![Screenshot (28)](https://user-images.githubusercontent.com/42043257/121522326-9f8d6d00-ca12-11eb-8b4c-addea398a093.png)
![Screenshot (30)](https://user-images.githubusercontent.com/42043257/121522328-a0be9a00-ca12-11eb-8aa3-4296e12fc251.png)

**Comment by lenhatminh0528** [comment]
> Is it possible to schedule local push notifications without setting up Firebase integration? I have changed the AndroidManifest.xml according to the README.
> 
> This is the error I get: ![grafik](https://user-images.githubusercontent.com/10599685/88297517-49331500-cd00-11ea-8c87-579bc03f1a16.png)
did you fix it? i'm fix it arcoding to readme.txt but it still not working. It sometime still crash the app and make error: inital firebase first.
