### ISSUE TITLE
Unknown argument type 'UNNotificationRequest' How to resolve?

### ISSUE THREAD

**Issue by xsephtion** [zo0r/react-native-push-notification#1860]
# Bug

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 24.97 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.13.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 7.2.0
## Steps To Reproduce

1. Trigger Local Notification
...

Describe what you expected to happen:

1. Local Notification Shows Up

## Reproducible sample code

First Error :

```bash
ExceptionsManager.js:179 Unknown argument type 'UNNotificationRequest' in method -[RNCPushNotificationIOS addNotificationRequest:]. Extend RCTConvert to support this type.
```

Second Error :

```bash
Exception '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array' was thrown while invoking addNotificationRequest on target RNCPushNotificationIOS with params (
        {
        badge = 10;
        body = "Message: rwrwr";
        category = "";
        id = 0;
        sound = "";
        title = "Angry Bird";
        userInfo =         {
            id = 0;
        };
    }
)
callstack: (
	0   CoreFoundation                      0x0000000183df8880 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1202304
	1   libobjc.A.dylib                     0x0000000198e13c50 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000183e68e1c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1662492
	3   CoreFoundation                      0x0000000183ce6e6c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 81516
	4   ModulenameHere                          0x0000000101521c9c -[RCTModuleMethod processMethodSignature] + 9832
	5   ModulenameHere                          0x0000000101526208 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 168
	6   ModulenameHere                          0x0000000101529f80 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 648
	7   ModulenameHere                          0x0000000101529b34 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 128
	8   ModulenameHere                          0x0000000101529aa8 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
	9   libdispatch.dylib                   0x00000001042abbcc _dispatch_call_block_and_release + 32
	10  libdispatch.dylib                   0x00000001042ad6c0 _dispatch_client_callout + 20
	11  libdispatch.dylib                   0x00000001042bcf34 _dispatch_main_queue_callback_4CF + 1000
	12  CoreFoundation                      0x0000000183d7411c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 659740
	13  CoreFoundation                      0x0000000183d6e120 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 635168
	14  CoreFoundation                      0x0000000183d6d21c CFRunLoopRunSpecific + 600
	15  GraphicsServices                    0x000000019b939784 GSEventRunModal + 164
	16  UIKitCore                           0x00000001867adee8 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 12357352
	17  UIKitCore                           0x00000001867b375c UIApplicationMain + 168
	18  ModulenameHere                          0x0000000100deca04 main + 128
	19  libdyld.dylib                       0x0000000183a2d6b0 21B19919-1334-38BC-B233-896E929945E0 + 5808
)
```

Here's my AppDelegate.m:

```bash
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

#import <Firebase.h>

#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>



static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"ModulenameHere"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;
  return YES;
}
-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  NSDictionary *userInfo = notification.request.content.userInfo;
   [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo
                                 fetchCompletionHandler:^void (UIBackgroundFetchResult result){}];

   // allow showing foreground notifications
   completionHandler(UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge);
   // or if you wish to hide all notification while in foreground replace it with
   // completionHandler(UNNotificationPresentationOptionNone);
}
// Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
 [RNCPushNotificationIOS didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}
// Required for the notification event. You must call the completion handler after handling the remote notification.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
// Required for the registrationError event.
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
 [RNCPushNotificationIOS didFailToRegisterForRemoteNotificationsWithError:error];
}
// Required for localNotification event
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  [RNCPushNotificationIOS didReceiveNotificationResponse:response];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

How can I resolve this problem? I have no prior experience on developing in Objective-C.

**Comment by xsephtion** [comment]
Resolved by verifying and re-installing podfile of @react-native-community/push-notification-ios.

**Comment by Mckiba** [comment]
I'm also having this issue. I tried removing my pods folder and doing pod install again but that doesn't fix it.

**Comment by Mckiba** [comment]
> Resolved by verifying and re-installing podfile of @react-native-community/push-notification-ios.

I'm also having this issue. I tried removing my pods folder and doing pod install again but that doesn't fix it.

**Comment by xsephtion** [comment]
> > Resolved by verifying and re-installing podfile of @react-native-community/push-notification-ios.
> 
> I'm also having this issue. I tried removing my pods folder and doing pod install again but that doesn't fix it.

Have you tried installing the push-notification-ios via npm? If that didn't help you can try to clear your build folder, remove the podfile/podfile.lock, then do pod install.

**Comment by Mckiba** [comment]
> > > Resolved by verifying and re-installing podfile of @react-native-community/push-notification-ios.
> > 
> > 
> > I'm also having this issue. I tried removing my pods folder and doing pod install again but that doesn't fix it.
> 
> Have you tried installing the push-notification-ios via npm? If that didn't help you can try to clear your build folder, remove the podfile/podfile.lock, then do pod install.

Yes I did install via npm. Cleaning the build folder, removing the podfile.lock and pods folder then doing pod install doesn't seem to work for me either.

**Comment by xsephtion** [comment]
> > > > Resolved by verifying and re-installing podfile of @react-native-community/push-notification-ios.
> > > 
> > > 
> > > I'm also having this issue. I tried removing my pods folder and doing pod install again but that doesn't fix it.
> > 
> > 
> > Have you tried installing the push-notification-ios via npm? If that didn't help you can try to clear your build folder, remove the podfile/podfile.lock, then do pod install.
> 
> Yes I did install via npm. Cleaning the build folder, removing the podfile.lock and pods folder then doing pod install doesn't seem to work for me either.

Can you provide me your react-native version and your xcode version?

**Comment by Mckiba** [comment]
react-native version 0.59.9 
Xcode 12.1

**Comment by Mckiba** [comment]
> > > > > Resolved by verifying and re-installing podfile of @react-native-community/push-notification-ios.
> > > > 
> > > > 
> > > > I'm also having this issue. I tried removing my pods folder and doing pod install again but that doesn't fix it.
> > > 
> > > 
> > > Have you tried installing the push-notification-ios via npm? If that didn't help you can try to clear your build folder, remove the podfile/podfile.lock, then do pod install.
> > 
> > 
> > Yes I did install via npm. Cleaning the build folder, removing the podfile.lock and pods folder then doing pod install doesn't seem to work for me either.
> 
> Can you provide me your react-native version and your xcode version, push-notification-ios and react-native-push-notification version?

react-native version 0.59.9
Xcode 12.1

**Comment by xsephtion** [comment]
> > > > > > Resolved by verifying and re-installing podfile of @react-native-community/push-notification-ios.
> > > > > 
> > > > > 
> > > > > I'm also having this issue. I tried removing my pods folder and doing pod install again but that doesn't fix it.
> > > > 
> > > > 
> > > > Have you tried installing the push-notification-ios via npm? If that didn't help you can try to clear your build folder, remove the podfile/podfile.lock, then do pod install.
> > > 
> > > 
> > > Yes I did install via npm. Cleaning the build folder, removing the podfile.lock and pods folder then doing pod install doesn't seem to work for me either.
> > 
> > 
> > Can you provide me your react-native version and your xcode version, push-notification-ios and react-native-push-notification version?
> 
> react-native version 0.59.9
> Xcode 12.1

That seem to be the problem, try upgrading to react-native 0.63, and xcode 12.4. 

I'm also using
"react-native-push-notification": "^7.2.0",
"@react-native-community/push-notification-ios": "^1.8.0",
for your reference.

**Comment by AlbertoMeQ** [comment]
Our project is at 0.59.9 and we cannot currently upgrade. What can we do? @xsephtion
