### ISSUE TITLE
cancelLocalNotifications() does not work on Android

### ISSUE THREAD

**Issue by jamesxabregas** [zo0r/react-native-push-notification#2100]
I have tested this extensively to see if there was something wrong with the way I was excuting cancelLocalNotification() but it does not appear that this works when providing an id on Android. I am executing it exactly per the documentation.

After adding debug logging into the Anrdoid pacakge I believe I have found the root cause of the issue. In `RNPushNotificationHelper.java` the method `cancelScheduledNotification(ReadableMap userInfo)` tries to extract the id from the provided JSON map and then find the correct notification to cancel. 

https://github.com/zo0r/react-native-push-notification/blob/6a81fba73b55f1ac975a2568486297102998150c/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L783-L786

The problem here is that the `matches` method in `RNPushNotificationAttributes.java` is being used incorrectly in this case. That method tries to match every element of the userInfo object with the notification it is iterating on which contains additional info such as the title, message etc. If the user has only provided the id attribute this always returns false.

https://github.com/zo0r/react-native-push-notification/blob/6a81fba73b55f1ac975a2568486297102998150c/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationAttributes.java#L200-L247

What is needed in this check is a simple method that matches the id's only. 

For instance something like this in `RNPushNotificationHelper.java`:
```
RNPushNotificationAttributes notificationAttributes = fromJson(notificationAttributesJson);
if (notificationAttributes.idMatches(userInfo)) {
    cancelScheduledNotification(id);
}
```

and this in `RNPushNotificationAttributes.java`

```
public boolean idMatches(ReadableMap userInfo) {
try {
    if(this.userInfo == null || userInfo == null) {
        return false;
    }
        return this.id.equals(userInfo.getString("id"));
    } catch(Exception e) {
        return false;
    }
}
```

I am happy to submit a pull request for this issue. I am working on my own fork at the moment.

**Comment by Dallas62** [comment]
Hi @jamesxabregas 
Did you cross check cases on iOS?
With multiple data in userInfo?

There is another method on Android which allow remove a scheduled notification only with the id.

**Comment by jamesxabregas** [comment]
I've tested this on iOS and it is not an issue. The issue only occurs on Android, and as explained it is due to an error in the Android implementation. I have also tested this with other data in the userInfo object but that doesn't make a difference.

The other method within the Android implementation is a private method. It is not accessible from the JavaScript interface, it is used internally by the public method of the same name that accepts the userInfo map.

https://github.com/zo0r/react-native-push-notification/blob/6a81fba73b55f1ac975a2568486297102998150c/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L794

I actually did wonder why cancelLocalNotifications() is implemented the way that it is. It would be far easier to just pass it a string with the id instead of having to parse the JSON object and extract the id.

**Comment by Dallas62** [comment]
I was thinking of:
https://github.com/zo0r/react-native-push-notification/blob/6a81fba73b55f1ac975a2568486297102998150c/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L690

But I will take a look ASAP.

**Comment by jamesxabregas** [comment]
I believe clearNotification has a different purpose as it removes a delivered notification from the Notification Center.

**Comment by garrettmaring** [comment]
I've also observed a difference in `cancelLocalNotifications()` between iOS & Android. While cancelling in this manner works for iOS, it seems as though calls to the method silently fail on Android causing the list of scheduled notifications to continue to grow.

Is it possible that we need to pass `channelId` to this cancel method?

![big](https://user-images.githubusercontent.com/8270120/129983381-1454b760-7605-4396-b1f1-329e97471df0.png)
![bigger](https://user-images.githubusercontent.com/8270120/129983384-ce40ba9c-3d47-4910-9eb3-686df949a18c.png)

**Comment by Dallas62** [comment]
Fixed in 8.0.0.
Regards

**Comment by dimadeveatii** [comment]
@Dallas62 this is still not working in latest v8.0.0.  
Please see https://github.com/zo0r/react-native-push-notification/issues/2122
