### ISSUE TITLE
No Method to unsubscribe

### ISSUE THREAD

**Issue by Moussawi7** [zo0r/react-native-push-notification#436]
Hi,
I read the documentation carefully but i didn't find a method to unregister from push notification.
How to achieve similar operation?!
Thank you.

**Comment by theohdv** [comment]
+1

**Comment by theohdv** [comment]
I tried to use the [unregister()](https://github.com/zo0r/react-native-push-notification/blob/6a4f70fa3754e511a7dfad4c86ae58db169e3c79/index.js#L108) method but it does not seem to work because i was still receiving notification push.

**Comment by ekimlinger** [comment]
PushNotification.cancelLocalNotifications(), or cancelAllLocalNotifications should work.

**Comment by thepelkus-too** [comment]
Testing this with a button that sends local notifications and a button that calls the unregister method, this appears to work for me. @theohdv , do you have more details about your case?

(Note that I don't have any responsibility for this project, but as a user of this library—which is working great for me so far; thanks to all contribs!—I'm just curious about cases where unregister may not work as expected.)

**Comment by theohdv** [comment]
Okay maybe it is because this method is only for local notifications. And to prevent your application to receive push notifications is a server side job I assume.

**Comment by kyaroru** [comment]
Finally I am able unsubscribe from Remote Notification 😉
Refer to : surialabs/react-native-push-notification@39d7adb

A scenario to subscribe and unsubscribe is to signIn & signOut
- When signIn, fire `requestPermissions()` (So a new deviceToken is generated & u have to update the token to your backend)
- When signOut, fire `abandonPermission()` (The token will be invalidated & your device will not receive any remote notification sending through that deviceToken)

**Comment by YahiaJabeur** [comment]
@kyaroru Thank you for the solution it works fine on iOS
But, I cant unsubscribe on android, I still receive notification after 
`PushNotification.requestPermissions()`
can you help?

**Comment by kyaroru** [comment]
u have to fire PushNotification.abandonPermission() using the code that I committed

**Comment by YahiaJabeur** [comment]
Thank you @kyaroru for the reply.
- I modified the plugin code source exactly like you did in your commit, I cleaned my android project with the command line `./gradlew clean`, but I still receive notification on Android after `PushNotification.abandonPermission()  `
Did I miss something more to do?

**Comment by kyaroru** [comment]
have you link the method abandonPermission in the index.android.js? alternatively, you can put console.log and see whether the method is invoked correctly

**Comment by JoseVf** [comment]
@kyaroru Can you make a PR with this feature? 😅

**Comment by JoseVf** [comment]
@YahiaJabeur Maybe try `PushNotification.abandonPermissions()` instead of `PushNotification.abandonPermission()`

**Comment by kyaroru** [comment]
> @kyaroru Can you make a PR with this feature? 😅

hmm.. will do in the near future 😛

**Comment by cogell** [comment]
Ran into this issue today on Android, neither `abandonPermissions` nor `unregister` releases an app from all previously subscribed topics/notifications

**Comment by Dallas62** [comment]
Hi, I think this issue is solved in recent release. Feel free to reopen if it's not the case.
