### ISSUE TITLE
details.date.toISOString is not a function

### ISSUE THREAD

**Issue by farid-ouachrar** [zo0r/react-native-push-notification#467]
Hello guys , i implemented the push notification in my project but i always get this problem 
![simulator screen shot jun 30 2017 12 04 37 pm](https://user-images.githubusercontent.com/20015003/27734848-4d362412-5d8c-11e7-8da9-e8ad9553dd9a.png)

here's my code  : 

`componentDidMount(){
    codePush.sync({
      updateDialog: true,
      installMode: codePush.InstallMode.IMMEDIATE
    })
    
    let date = new Date(Date.now() + (6 * 1000));

    PushNotification.localNotificationSchedule({
      message: "My Notification Message", // (required)
      date: (Platform.OS === 'ios') ? date.toISOString() : date // in 60 secs
    })
  }`

Note that i only get this problem on ios , android is working fine

**Comment by varungupta85** [comment]
Don't set date as `date.toISOString()`. Send the `date` object as is for both iOS and Android. So, do

```javascript
let date = new Date(Date.now() + (6 * 1000));

PushNotification.localNotificationSchedule({
  message: "My Notification Message", // (required)
  date: date // in 60 secs
})
```

**Comment by farid-ouachrar** [comment]
@varungupta85 that's the first thing i did but this is what i get : 

![simulator screen shot jun 30 2017 2 06 47 pm](https://user-images.githubusercontent.com/20015003/27739221-685b963a-5d9d-11e7-85e7-d3865c865a75.png)

**Comment by varungupta85** [comment]
This is a separate issue. Your earlier call stack was occurring because you were not sending the date object. I don't use this lib for iOS, so I don't know about this call stack.

**Comment by edencakir** [comment]
@varungupta85 yes I'm experiencing the same thing after that change, a few months ago this was working. I'm afraid its broken now. @farid-ouachrar 

Can someone have a look at this?

**Comment by varungupta85** [comment]
Do you guys have the latest version? This may be related to the `number` field not set in the details object which was fixed in this commit
https://github.com/zo0r/react-native-push-notification/commit/6a4f70fa3754e511a7dfad4c86ae58db169e3c79#diff-168726dbe96b3ce427e7fedce31bb0bc

**Comment by farid-ouachrar** [comment]
Thank you @varungupta85 , it fixed the problem

**Comment by danleveille** [comment]
Just for extra reference: I upgraded to 3.0.0, but it did not fix it.

However, @varungupta85's first suggestion worked for me.

**Comment by mvshashank08** [comment]
I tried the fix given by @varungupta85 . I've got this error.
![simulator screen shot 22-jul-2017 12 24 57 pm](https://user-images.githubusercontent.com/14188424/28489134-969b2c9e-6ed8-11e7-9102-ddac763fbd48.png)

I edited the `index.js` at `/node-modules/react-native-push-notification/index.js`

![screen shot 2017-07-22 at 12 31 52 pm](https://user-images.githubusercontent.com/14188424/28489147-f7e8a04e-6ed8-11e7-8964-2f1881a0725c.png)

**Comment by joaom182** [comment]
I have the same issue, anyone fix it?
